var x;
var x1;
var x2;
var x3;
var x4;
var x5;
x = 1234.234767;
x1 = "hasan";
x2 = "ali";
x3 = (x == 1234.234767);
x4 = "Gulshan-1";
x5 = x1.concat(x2);
console.log("Your id:".concat(x, ", UserName:").concat(x5, ", Account activated: ").concat(x3, " \n Branch name: ").concat(x4));
console.log("full name", x5.split(" "));
console.log("full name", x5.toUpperCase());
console.log("full name", x5.toLowerCase());
console.log("user id", x.toFixed(3));
